### ISSUE TITLE
teleport_config_template isn't used

### ISSUE THREAD

**Issue by ClementGautier** [mdsketch/ansible-teleport#2]
Hi, it seems the default template for the config is never used, the variable `teleport_config_template` is not used [here](https://github.com/mdsketch/ansible-teleport/blob/main/tasks/main.yml#L67) thus making the use of the default template bogus. The worst part is that if you disable that with the `teleport_template_config` flag then the service doesn't start because it assume you have a config:

```
Apr 12 15:32:35 bigdaddy systemd[1]: Started Teleport SSH Service.
Apr 12 15:32:35 bigdaddy teleport[1092728]: ERROR: path '/etc/teleport.yaml' does not exist
Apr 12 15:32:35 bigdaddy systemd[1]: teleport.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 15:32:35 bigdaddy systemd[1]: teleport.service: Failed with result 'exit-code'.
```

Using the variable like you did for the service fixes the error.

**Comment by mdsketch** [comment]
Hey nice catch. That's actually the behaviour I wanted, I guess I overlooked it and assumed it worked because I happen to name my template the same as in the role. 
I'll merge your PR👍

**Comment by mdsketch** [comment]
It's been updated on Galaxy so should be good to go if you pull it.

**Comment by ClementGautier** [comment]
thanks for the quick merge :)
